<?xml version="1.0" encoding="utf-8"?><Database Name="GestionPedidos" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-H2L8A0S\SQLSERVERMPS;Initial Catalog=GestionPedidos;Persist Security Info=True;User ID=sa" SettingsObjectName="WpfVideo103.Properties.Settings" SettingsPropertyName="CrudLinqSQLConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Empresas" Member="Empresas">
    <Type Name="Empresas">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Empresas_Empleados" Member="Empleados" ThisKey="id" OtherKey="idEmpresa" Type="Empleados" />
    </Type>
  </Table>
  <Table Name="dbo.Empleados" Member="Empleados">
    <Type Name="Empleados">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellidos" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idEmpresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Empleados_CargoEmpleados" Member="CargoEmpleados" ThisKey="id" OtherKey="idEmpleado" Type="CargoEmpleados" />
      <Association Name="Empresas_Empleados" Member="Empresas" ThisKey="idEmpresa" OtherKey="id" Type="Empresas" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cargos" Member="Cargos">
    <Type Name="Cargos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Cargos_CargoEmpleados" Member="CargoEmpleados" ThisKey="id" OtherKey="idCargo" Type="CargoEmpleados" />
    </Type>
  </Table>
  <Table Name="dbo.CargoEmpleados" Member="CargoEmpleados">
    <Type Name="CargoEmpleados">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idEmpleado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idCargo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Cargos_CargoEmpleados" Member="Cargos" ThisKey="idCargo" OtherKey="id" Type="Cargos" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Empleados_CargoEmpleados" Member="Empleados" ThisKey="idEmpleado" OtherKey="id" Type="Empleados" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>